### ISSUE TITLE
Is there a possibility to support Android?

### ISSUE THREAD

**Issue by MicJeRon** [mafe72/Retroflag-NESPi-Fan-Control-Board#1]
I use different operating systems with my NESPI 4. Would it be possible to use the fan controller with the [Konstakang LineageOS build](https://konstakang.com/devices/rpi4/LineageOS19/)? However, I read that [Python is not supported](https://raspberrypi.stackexchange.com/questions/136901/how-do-i-control-a-fan-attached-to-gpio-pins-on-android) by Android.

**Comment by mafe72** [comment]
I have no plans to support Android.
