### ISSUE TITLE
Progressive Fan Speeds

### ISSUE THREAD

**Issue by ivan-pinatti** [mafe72/Retroflag-NESPi-Fan-Control-Board#2]
Hello,

Would be possible with the current NESPi Fan Control board circuitry and code, in a Retroflag MegaPI Case, to actually instead of having the fan at full power when reached the `maxTEMP`, to have it progressively increasing the speed up to the max RPM? Example;

- Temperature is `<40°` - FAN is **_OFF_**
- Temperature is `>40° AND <44°` - FAN **_ON at 25%_**
- Temperature is `>45° AND <49°` - FAN **_ON at 50%_**
- Temperature is `>50° AND <54°` - FAN **_ON at 75%_**
- Temperature is `>55°` - FAN **_ON at 100%_**

**Comment by mafe72** [comment]
I have added Incremental Fan Speed Control on the latest version of the script.

**Comment by ivan-pinatti** [comment]
Amazing!
